### ISSUE TITLE
Great website

### ISSUE THREAD

**Issue by jenath** [fac-14/IJKL-Team-Site#24]
- Your website is very clear and great work with responsiveness. 
- You may want to add some more meta data in the head section such as authors name & description.

https://www.w3schools.com/tags/tag_meta.asp

**Comment by helenzhou6** [comment]
Yes!! 💯😊I love how responsive it is!

**Comment by developess** [comment]
Thank you so much for all your comments @jenath! Hopefully we've addressed them all :)
