### ISSUE TITLE
Accessibility: mobile nav items read as "internal links"

### ISSUE THREAD

**Issue by njons** [fac-14/IJKL-Team-Site#26]
We noticed that in mobile the nav changes to icons, which works really well, but the icons don't have names in screen readers and its hard to know where they go.

**Comment by njons** [comment]
![screen shot 2018-07-06 at 10 44 53](https://user-images.githubusercontent.com/30963614/42372276-bbec6e4c-8109-11e8-8a93-18f4381f79dd.png)

Also caught in lighthouse audit

**Comment by sima-qian** [comment]
We tried several times to fix this towards the end of the day but couldn't get anything to work 😞

**Comment by SleepySheepy172** [comment]
Added aria-labels to the icons
