### ISSUE TITLE
Question: Form in the footer

### ISSUE THREAD

**Issue by njons** [fac-14/IJKL-Team-Site#34]
We'd like to know more about why you chose to put the form in the footer together with the copyright sign (because we did not).

**Comment by helenzhou6** [comment]
👍
I would consider putting the form outside of the footer tag and perhaps using a `<section>` tag instead for the form, and the `<footer>` would just contain the Copyright information.

**Comment by sima-qian** [comment]
My argument was that the contact form is not part of the main content of the page, so should go in the footer -- it might be one of those things that's fairly arbitrary
