### ISSUE TITLE
Table vs setting it out in css

### ISSUE THREAD

**Issue by sbinlondon** [fac-14/IJKL-Team-Site#48]
https://github.com/fac-14/IJKL-Team-Site/blob/7d3135c79171014a4104cdd6b259fa7a34c56b3d/index.html#L150

I'm interested to know about your decision to set out these elements in a table rather than styling it with grid/flex in CSS 🤔

**Comment by developess** [comment]
This was just for convenience tbh! We started using flexbox and thought table would be quicker. 
Given more time we might change it to flex, although table would probably have better browser support.
