### ISSUE TITLE
Instead of div for spacing

### ISSUE THREAD

**Issue by jenath** [fac-14/IJKL-Team-Site#53]
- **Line 63** HTML
`<div class="space-div-1"></div>`

- **Lines 155 - 158** CSS
```
.team {
  width: 90vw;
  margin: auto;
}
```
You may want to add a `margin-top : 50px; ` to  the `.team` class and delete the div with a space class, please let me know if I am wrong and you have done this for a specific reason.

**Comment by sima-qian** [comment]
Good point -- now changed 🙇
